name: inception

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    restart: always
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress: # verifier si erreur en ajoutant un commentaire avec l'user
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    restart: always
    env_file: .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_pwd
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
      - reverse-proxy
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    restart: always
    env_file: .env
    ports:
      # - 80:80 
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - reverse-proxy
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rems/data/mariadb
    # name: ?
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rems/data/wordpress
    # name: ?

networks:
  inception:
    driver: bridge
    # name: ?
  reverse-proxy:
    driver: bridge

secrets:
  db_root_password:
    file: ../srcs/secrets/db_root_password.txt
  db_password:
    file: ../srcs/secrets/db_password.txt
  wp_admin_password:
    file: ../srcs/secrets/wp_admin_password.txt
  wp_user_pwd:
    file: ../srcs/secrets/wp_user_pwd.txt
